### ISSUE TITLE
已被盗传至 Edge 扩展商店

### ISSUE THREAD

**Issue by Geeyun-JY3** [fhefh2015/Fast-GitHub#13]
路过顺便提醒：https://microsoftedge.microsoft.com/addons/detail/ljceflkaahacpphaioldeledefadpmdp

**Comment by fhefh2015** [comment]
您好 已反馈 但是一直未收到微软的邮件回复~

**Comment by Geeyun-JY3** [comment]
这个家伙盗传的扩展都已经没了
