### ISSUE TITLE
去掉hao123的首页

### ISSUE THREAD

**Issue by kaiccc** [fhefh2015/Fast-GitHub#14]
理解这种行为，能不能控制下打开的次数，不要每次打开首页都是hao123

不想因为一个问题放弃了这么好的插件。

**Comment by fhefh2015** [comment]
您好 chrome商店版本没有做任何影响用户体验的多余操作

微软商店的同名插件 并非本人发布
![image](https://user-images.githubusercontent.com/14891797/105451395-74022400-5cb7-11eb-81ae-0befe8ecfffe.png)

**Comment by dds2333** [comment]
直接举报 Edge商店 那狗比了，不知道有没有用，搜了"heaven0sky"，github有这个用户而且还是国内的，应该是这逼佬

**Comment by dds2333** [comment]
虽然github下载一直用梯子，但看到作者开源的项目被狗日的拿去恰烂饭，不能忍

**Comment by DanielYWoo** [comment]
逼样的heaven0sky。。。。

**Comment by fhefh2015** [comment]
heaven0sky这位作者提交的版本，已经下架

我在微软Edge商店已提交最新版 目前正在审核之中
