### ISSUE TITLE
Windows如何配置SSH？

### ISSUE THREAD

**Issue by Aric-Sun** [fhefh2015/Fast-GitHub#16]
本地没有config文件
```bash
~/.ssh
$ ls
id_rsa  id_rsa.pub  known_hosts
```

**Comment by ccicnce113424** [comment]
https://docs.github.com/cn/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by Aric-Sun** [comment]
> https://docs.github.com/cn/github/authenticating-to-github/connecting-to-github-with-ssh

thx，已经成功。速度500KiB/s
