### ISSUE TITLE
貌似在Vivaldi会导致GitHub页面卡死

### ISSUE THREAD

**Issue by yswtrue** [fhefh2015/Fast-GitHub#19]

**Comment by fhefh2015** [comment]
v1.2.1
解决Github pjax问题

v1.2.3
移除了v1.2.1中部分代码 可能是这个原因引起的

v1.2.3已发布 chrome正在审核中

**Comment by fhefh2015** [comment]
v1.2.3已发布 
@yswtrue 可以尝试一下~

**Comment by yswtrue** [comment]
更新之后暂时没发现原来的问题了
