### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by imba-tjd** [fhefh2015/Fast-GitHub#2]
1. “进入加速Release页面”没有作用，release用的是亚马逊的s3，会自动重定向过去。不需要此按钮

2. “加速 克隆和下载”中的`cnpmjs.org`的url不正确，以本repo为例，现在是`https://github.com.cnpmjs.org/https://github.com/fhefh2015/Fast-GitHub.git`

3. `Cloudflare Workers通道加速`里有两个连续斜杠

4. `git clone https://github.91chifun.workers.dev/https://github.com/fhefh2015/Fast-GitHub.git` 会自动重定向到`https://github.com.cnpmjs.org/fhefh2015/Fast-GitHub.git`，但是`curl -I https://github.91chifun.workers.dev/https://github.com/fhefh2015/Fast-GitHub.git`却是404，迷。我认为这个workers不支持打开网页，既然clone又是重定向到cnpmjs的，那只有下载release能用。

**Comment by fhefh2015** [comment]
https://github.com/hunshcn/gh-proxy 配合CF搭建的~
