### ISSUE TITLE
加速下载ZIP 按钮无效

### ISSUE THREAD

**Issue by jiangjiali** [fhefh2015/Fast-GitHub#34]
加速下载ZIP 按钮无效

**Comment by gagmeng** [comment]
同样反映下载ZIP已失效

**Comment by fhefh2015** [comment]
@jiangjiali 
@gagmeng 
感谢反馈
已修复
chrome版本正在审核

**Comment by fhefh2015** [comment]
@jiangjiali
@gagmeng
商店版本已审核通过 请升级
v1.3.2

**Comment by fhefh2015** [comment]
@zaaack v1.3.4已提供 感谢反馈
