### ISSUE TITLE
原理是用shadowsocket链接博主的服务器构建加速通道吗？貌似对GitHub页面加载没用，得用vpn，这样不能加速github网页也没啥意义

### ISSUE THREAD

**Issue by w13411965905** [fhefh2015/Fast-GitHub#35]
原理是用shadowsocket链接博主的服务器构建加速通道吗？貌似对GitHub页面加载没用，得用vpn，这样不能加速github网页也没啥意义

**Comment by fhefh2015** [comment]
hunshcn/gh-proxy: github release、archive以及项目文件的加速项目 
https://github.com/hunshcn/gh-proxy
