### ISSUE TITLE
当前版本在部分github页面会出现行不对齐的问题

### ISSUE THREAD

**Issue by cdmikechen** [fhefh2015/Fast-GitHub#38]
我在一些git的commits页面会出现按钮不对齐的问题，原来好像没留意有这样的问题，不知道是不是github修改了部分样式导致的。
截图如下：

![image](https://user-images.githubusercontent.com/12069428/145503472-4fdf545f-aef7-4058-bf6a-bce6d2547c69.png)

**Comment by HuangYan-lz** [comment]
您好，邮件已经收到，我将尽快给你回复。

**Comment by lxdhhy** [comment]
谢谢，您的邮件已收到,我会尽快给回复！

**Comment by fhefh2015** [comment]
@cdmikechen 
感谢反馈 
下个版本修复该问题

**Comment by fhefh2015** [comment]
@cdmikechen 
v1.3.5以解决

**Comment by HuangYan-lz** [comment]
您好，邮件已经收到，我将尽快给你回复。
