### ISSUE TITLE
进入子目录，重新回到主目录，图标重复复

### ISSUE THREAD

**Issue by Hercules11** [fhefh2015/Fast-GitHub#39]
![image](https://user-images.githubusercontent.com/43318823/146460202-aaa1efff-6318-47ed-96e5-400002c63e77.png)

**Comment by fhefh2015** [comment]
楼主 你用的哪个版本？
刚刚测试v1.3.4 反馈问题无法重现
详情见视频演示

https://user-images.githubusercontent.com/14891797/146474698-096b756b-fad9-44f7-982e-a5e36662fa13.mp4

**Comment by Hercules11** [comment]
版本也是1.3.4
我回到主目录，是通过浏览器的回退 **←** 
后退 **←**， 前进 **→** 多点击几次，就这样了

**Comment by fhefh2015** [comment]
好的

我看看 感谢老铁的反馈

**Comment by yunnysunny** [comment]
已经提交 pull request https://github.com/fhefh2015/Fast-GitHub/pull/40

**Comment by fhefh2015** [comment]
@yunnysunny 
感谢贡献，v1.3.5已经解决这个问题了

@Hercules11 
v1.3.5已经解
