### ISSUE TITLE
这个自定义域名是什么意思

### ISSUE THREAD

**Issue by mendax1234** [fhefh2015/Fast-GitHub#43]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/62934294/153703764-08d8dfcc-2546-4373-af6b-ea3141321574.png">
我发现如果不修改的话不太稳定，有没有更稳定的域名

**Comment by fhefh2015** [comment]
参考该文章
开源分享：gh-proxy——基于cloudflare workers的GitHub文件加速 - Hunsh's Blog 
https://hunsh.net/archives/23/

**Comment by AXFOX** [comment]
> 我看了，但好像没太看懂，大佬能解释一下吗

他说的是自建一个cf代理下载站，自定义选择用自己的站
