### ISSUE TITLE
点击加速下载出现NOT FOUND

### ISSUE THREAD

**Issue by whwdzg** [fhefh2015/Fast-GitHub#48]
![image](https://user-images.githubusercontent.com/91038761/161422857-d0c8560a-e191-412a-b999-c4ce05443dd9.png)

**Comment by fhefh2015** [comment]
有2个原因：

提供加速的站点额度用完了 等第二天使用就好了
这个网址不提供加速服务了
可以尝试多添加几个加工加速的网站 试一试
