### ISSUE TITLE
插件更新后，出现不美好效果

### ISSUE THREAD

**Issue by lion-no-back** [fhefh2015/Fast-GitHub#55]
这是我今天花了一个小时排查出的结果，是插件更新后，上github，有些按钮会出现重影，以下是实例

![](https://i2.100024.xyz/2022/07/28/r5ch5x.webp)

![](https://i2.100024.xyz/2022/07/28/r6tt8c.webp)

**Comment by fhefh2015** [comment]
您好 感谢您的反馈

插件代码没有做任何修改

只是根据Chrome商店反馈 修改了`版本号`和`描述说明`

<img width="359" alt="CleanShot 2022-07-28 at 16 47 55@2x" src="https://user-images.githubusercontent.com/14891797/181463471-40c97667-3e6d-4d54-8a0f-56a2218c5ed2.png">

---

在Chrome无痕模式下，用v1.3.7版本进行测试 看着效果是正常的

您在无痕模式下 显示样式也有问题吗？

<img width="682" alt="CleanShot 2022-07-28 at 16 54 45@2x" src="https://user-images.githubusercontent.com/14891797/181464916-c326b31b-402f-46d5-aedb-204157966515.png">


<img width="336" alt="CleanShot 2022-07-28 at 16 53 23@2x" src="https://user-images.githubusercontent.com/14891797/181464603-b78c0213-15f6-487b-bc50-1b27b59e090a.png">


![CleanShot 2022-07-28 at 16 52 45@2x](https://user-images.githubusercontent.com/14891797/181464518-3fcd92dd-2c1d-4f88-aa60-91d9da4e3626.png)


![CleanShot 2022-07-28 at 16 51 44@2x](https://user-images.githubusercontent.com/14891797/181464362-b5a77d52-4cf6-4af8-8ccf-825d1747d6cb.png)

**Comment by lion-no-back** [comment]
是我敏感了，我更新就出问题了，我又重新试了下，之前可能认为是扩展冲突，或者脚本冲突，结果是扩展和脚本冲突，原来没有的，就玄学吧，不能和下面脚本一起使用，不然就会有以上效果

![](https://i2.100024.xyz/2022/07/28/s6m078.webp)
