### ISSUE TITLE
为何push代码也会带上url前缀？

### ISSUE THREAD

**Issue by cccattaccc** [fhefh2015/Fast-GitHub#56]
我在vscode push代码时也会加上网站的前缀，这样会导致我的github验证失败从而无法Push代码，是哪里需要设置吗？
最后的url是这样的
![image](https://user-images.githubusercontent.com/37857458/183283544-13afb39f-6618-4679-90e2-970505a4773c.png)

**Comment by fhefh2015** [comment]
这个问题 没有遇到过 囧

一般只用来下载  没有尝试过git push
