### ISSUE TITLE
Assets过多的情况下，点击显示过多后无加速下载按钮

### ISSUE THREAD

**Issue by supery-chen** [fhefh2015/Fast-GitHub#59]
初始界面有加速下载按钮
![image](https://user-images.githubusercontent.com/54849153/194733515-0d60628c-b512-4471-8243-6650c1879001.png)
点击show all assets后无加速下载按钮
![image](https://user-images.githubusercontent.com/54849153/194733520-8c8df101-bd37-4e67-8cb5-cf0f2d721c92.png)

**Comment by fhefh2015** [comment]
<img width="1192" alt="CleanShot 2022-11-14 at 18 48 46@2x" src="https://user-images.githubusercontent.com/14891797/201641525-8c51a0c6-d98f-46e3-b71b-c08a3fe0ffac.png">
问题已解决 Chrome商店可以更新 Edge商店还在审核
