### ISSUE TITLE
release 下载展开链接不支持加速

### ISSUE THREAD

**Issue by sdragonx** [fhefh2015/Fast-GitHub#60]
[200598](https://github.com/ibmruntimes/semeru18-binaries/releases)
这个网址后面的下载展开后，链接无法加速。

**Comment by fhefh2015** [comment]
问题已解决 可以在Chrome商店更新了 Edge商店还在审核

<img width="1192" alt="CleanShot 2022-11-14 at 18 48 46@2x" src="https://user-images.githubusercontent.com/14891797/201641436-13712848-6f13-492f-a2f9-bb0bab2fd77e.png">
