### ISSUE TITLE
加速通道显示404File not found

### ISSUE THREAD

**Issue by LiuBinzhe** [fhefh2015/Fast-GitHub#61]
![image](https://user-images.githubusercontent.com/115980764/197098063-59c776ae-f50c-4c15-9cb5-600b45ad8cf6.png)

**Comment by fhefh2015** [comment]
有2个原因：
1. 提供加速的站点额度用完了 等第二天使用就好了
2. 这个网址不提供加速服务了 

可以尝试多添加几个加工加速的网站 试一试
