### ISSUE TITLE
Realese 页面 点击 "Show all 14 assets" 后, 加速按钮消失.

### ISSUE THREAD

**Issue by YYMMYB** [fhefh2015/Fast-GitHub#62]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases

我是在这个页面发现的这个问题。

**Comment by lrs95** [comment]
确实有这问题，而且下面的其他隐藏起来的版本点开后也没有加速按钮

**Comment by fhefh2015** [comment]
@YYMMYB 
@lrs95 
问题已解决 可以在Chrome商店更新了 Edge商店还在审核
