### ISSUE TITLE
加速通道个数

### ISSUE THREAD

**Issue by NoodlesGentleman** [fhefh2015/Fast-GitHub#71]
![image](https://user-images.githubusercontent.com/32062284/206145848-a9c70516-c6e1-4ed2-932d-a9d4ae47ac0e.png)

现在是只显示一个加速通道了吗？之前是多个，更新后变成一个了。配置里添加为多个也是这样

**Comment by fhefh2015** [comment]
<img width="187" alt="CleanShot 2022-12-13 at 19 22 04@2x" src="https://user-images.githubusercontent.com/14891797/207304887-7893bc95-9ec5-4881-b0fe-16f42faf49bd.png">
设置页面 默认为1，可自行更改

**Comment by NoodlesGentleman** [comment]
好了，谢谢
