### ISSUE TITLE
生成的加速地址，默认带了github的地址了

### ISSUE THREAD

**Issue by xuexuguang** [fhefh2015/Fast-GitHub#77]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/22195079/211237835-b0a54a72-41bc-4d43-a047-1eba895f9911.png">

**Comment by fhefh2015** [comment]
URL链接组成：https://基于gh-proxy网址/github地址

详情参考
https://github.com/hunshcn/gh-proxy
