### ISSUE TITLE
XML error: syntax error

### ISSUE THREAD

**Issue by Sunny-117** [fhefh2015/Fast-GitHub#79]
![image](https://user-images.githubusercontent.com/73089592/213638084-eb687add-313f-4352-b110-99a6c93ed826.png)

**Comment by fhefh2015** [comment]
https://github.com/fhefh2015/Fast-GitHub/issues/44
貌似这个源出问题了 在这个里面选一个看看

**Comment by Sunny-117** [comment]
ok thanks
