### ISSUE TITLE
Chromium的加速升级到1.5.10后， 进入github网站，不显示加速栏了。

### ISSUE THREAD

**Issue by lk1983823** [fhefh2015/Fast-GitHub#80]
Chromium的加速升级到1.5.10后， 进入github网站，不显示加速栏了。只有原始的code链接，没有加速栏了。This can read and change site data 选择的 on github.com

**Comment by fhefh2015** [comment]
删除 在重新安装看看 
https://github.com/fhefh2015/Fast-GitHub/issues/70#issuecomment-1319412849

**Comment by lk1983823** [comment]
> 删除插件 在重新安装 应该可以 有群友遇到类似问题 [#70 (comment)](https://github.com/fhefh2015/Fast-GitHub/issues/70#issuecomment-1319412849)

@fhefh2015 
重新安装后，图像一直是灰色
![image](https://user-images.githubusercontent.com/20237650/215251046-78167187-4b82-418d-8ef7-17f3ca5d115d.png)

**Comment by fhefh2015** [comment]
额 这就不知道是什么原因导致了~
可以尝试使用一下油猴版本的 
Github 增强 - 高速下载 
https://greasyfork.org/zh-CN/scripts/412245-github-%E5%A2%9E%E5%BC%BA-%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD
