### ISSUE TITLE
请问点击Options后如何配置？界面好像不一致了

### ISSUE THREAD

**Issue by sunnyykk** [fhefh2015/Fast-GitHub#81]
这是我点击Options按钮后的界面，与[说明](https://github.com/fhefh2015/Fast-GitHub/issues/44)中的界面不一致呀。
![image](https://user-images.githubusercontent.com/34845957/219840988-f7316532-a862-406a-82b4-8b7f86136960.png)

**Comment by fhefh2015** [comment]
这个是老版本~
可以卸载了 在对应浏览器插件商店安装

新版本功能更多 体验更好~

**Comment by sunnyykk** [comment]
Thx~~
